defmodule Mix.Tasks.Concept.Docs.McpSurface do
  @moduledoc """
  Generates `docs/mcp_surface.md` from Ash action metadata.

  ## Usage

      mix concept.docs.mcp_surface         # regenerate the file
      mix concept.docs.mcp_surface --check # exit non-zero if drifted

  The generated file is the auto-derived source of truth for the MCP
  surface. It is committed to the repo so PR review surfaces additions
  and renames. CI runs the `--check` variant via the `precommit` alias.

  Built per FEAT-063 (PLAN-007). See `docs/mcp_parity.md`.
  """
  use Mix.Task

  @shortdoc "Generates docs/mcp_surface.md from Ash action metadata."

  @output_path "docs/mcp_surface.md"

  @impl Mix.Task
  def run(args) do
    Mix.Task.run("app.start")

    {opts, _, _} = OptionParser.parse(args, strict: [check: :boolean])

    new = render_markdown()
    check? = opts[:check] == true

    case {File.read(@output_path), check?} do
      {{:ok, ^new}, _} ->
        Mix.shell().info("docs/mcp_surface.md up to date.")

      {{:ok, _other}, true} ->
        Mix.raise(
          "docs/mcp_surface.md is out of date. Run `mix concept.docs.mcp_surface` to regenerate."
        )

      {{:error, :enoent}, true} ->
        Mix.raise(
          "docs/mcp_surface.md does not exist. Run `mix concept.docs.mcp_surface` to generate it."
        )

      _ ->
        File.write!(@output_path, new)
        Mix.shell().info("Wrote #{@output_path}.")
    end
  end

  @doc false
  # Public so the integration parity test (FEAT-063) can compare committed
  # vs live output without running the task as a side effect.
  def render_markdown do
    domains = Application.get_env(:concept, :ash_domains, [])

    header =
      """
      # MCP surface

      _This file is auto-generated by `mix concept.docs.mcp_surface`._
      _Do not edit by hand. See `docs/mcp_parity.md` for the architectural principle._

      Every public Ash action with a `description` projects to one MCP tool via
      `Concept.AutoTools`. Workspace tenancy is enforced by
      `ConceptWeb.Plugs.MCPWorkspaceContext`. Actor + tenant filter what each
      caller sees.

      ---
      """

    body =
      domains
      |> Enum.sort_by(&inspect/1)
      |> Enum.map(&render_domain/1)
      |> Enum.reject(&(&1 == ""))
      |> Enum.join("\n")

    header <> "\n" <> body
  end

  defp render_domain(domain) do
    tools = AshAi.Info.tools(domain)
    resources = AshAi.Info.mcp_action_resources(domain)

    if tools == [] and resources == [] do
      ""
    else
      [
        "## " <> inspect(domain),
        "",
        if(tools == [], do: "", else: render_tools_section(tools)),
        if(resources == [], do: "", else: render_resources_section(resources)),
        "---",
        ""
      ]
      |> Enum.reject(&(&1 == ""))
      |> Enum.join("\n")
    end
  end

  defp render_tools_section(tools) do
    rows =
      tools
      |> Enum.sort_by(& &1.name)
      |> Enum.map(&render_tool/1)
      |> Enum.join("\n\n")

    "### Tools (" <> Integer.to_string(length(tools)) <> ")\n\n" <> rows <> "\n"
  end

  defp render_tool(tool) do
    action = Ash.Resource.Info.action(tool.resource, tool.action)
    description = tool.description || (action && action.description) || "_no description_"

    args =
      case action do
        nil ->
          ""

        %{arguments: args} ->
          args
          |> Enum.filter(& &1.public?)
          |> case do
            [] ->
              ""

            args ->
              rows =
                Enum.map(args, fn arg ->
                  type = arg.type |> inspect() |> String.replace_prefix("Ash.Type.", "")

                  req =
                    if arg.allow_nil? == false, do: "required", else: "optional"

                  desc = arg.description || "_no description_"
                  "  - `#{arg.name}` (`#{type}`, #{req}) — #{desc}"
                end)

              "\n\n**Arguments:**\n\n" <> Enum.join(rows, "\n")
          end
      end

    """
    #### `#{tool.name}`

    #{description}

    - **Resource**: `#{inspect(tool.resource)}`
    - **Action**: `:#{tool.action}` (#{action_type_label(action)})#{args}
    """
  end

  defp action_type_label(nil), do: "?"
  defp action_type_label(%{type: type}), do: Atom.to_string(type)

  defp render_resources_section(resources) do
    rows =
      resources
      |> Enum.sort_by(& &1.name)
      |> Enum.map(fn r ->
        """
        #### `#{r.uri}`

        #{r.description || "_no description_"}

        - **Resource**: `#{inspect(r.resource)}`
        - **Action**: `:#{r.action}`
        - **MIME**: `#{r.mime_type || "text/plain"}`
        """
      end)
      |> Enum.join("\n")

    "### MCP resources (" <> Integer.to_string(length(resources)) <> ")\n\n" <> rows <> "\n"
  end
end
