defmodule Concept.Repo.Migrations.Wave4AgentTurnBudget do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      add :agent_turn_budget, :bigint, null: false, default: 5
    end
  end

  def down do
    alter table(:conversations) do
      remove :agent_turn_budget
    end
  end
end
