defmodule Concept.Repo.Migrations.AddIngestionJobsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:knowledge_ingestion_jobs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :workspace_id, :uuid, null: false
      add :page_id, :uuid, null: false
      add :op, :text, default: "upsert"
      add :state, :text, null: false, default: "queued"
      add :scheduled_at, :utc_datetime_usec
      add :started_at, :utc_datetime_usec
      add :finished_at, :utc_datetime_usec
      add :chunk_count, :bigint
      add :embed_tokens, :bigint
      add :error_kind, :text
      add :error_message, :text
      add :attempt, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create index(:knowledge_ingestion_jobs, [:workspace_id, :page_id])

    create index(:knowledge_ingestion_jobs, [:workspace_id, :state])
  end

  def down do
    drop_if_exists index(:knowledge_ingestion_jobs, [:workspace_id, :state])

    drop_if_exists index(:knowledge_ingestion_jobs, [:workspace_id, :page_id])

    drop table(:knowledge_ingestion_jobs)
  end
end
