defmodule Concept.Repo.Migrations.Wave3Threads do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      add :parent_conversation_id,
          references(:conversations,
            column: :id,
            name: "conversations_parent_conversation_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :seed_message_id, :uuid
    end
  end

  def down do
    drop constraint(:conversations, "conversations_parent_conversation_id_fkey")

    alter table(:conversations) do
      remove :seed_message_id
      remove :parent_conversation_id
    end
  end
end
