defmodule Concept.Repo.Migrations.AddConversationHost do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      add :host_type, :text, null: false, default: "workspace"
      add :host_id, :uuid
    end
  end

  def down do
    alter table(:conversations) do
      remove :host_id
      remove :host_type
    end
  end
end
