defmodule Concept.Repo.Migrations.Wave2MessageBlocks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:blocks) do
      modify :page_id, :uuid, null: true

      add :message_id,
          references(:messages,
            column: :id,
            name: "blocks_message_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create index(:blocks, [:workspace_id, :message_id, :position])

    create constraint(:blocks, :blocks_one_container,
             check: """
               num_nonnulls(page_id, message_id) = 1
             """
           )
  end

  def down do
    drop_if_exists constraint(:blocks, :blocks_one_container)

    drop constraint(:blocks, "blocks_message_id_fkey")

    drop_if_exists index(:blocks, [:workspace_id, :message_id, :position])

    alter table(:blocks) do
      remove :message_id
      modify :page_id, :uuid, null: false
    end
  end
end
