defmodule Concept.Repo.Migrations.CreateWorkflowEngine do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workflows, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :workspace_id, :uuid, null: false
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create table(:workflow_states, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :workspace_id, :uuid, null: false

      add :workflow_id,
          references(:workflows,
            column: :id,
            name: "workflow_states_workflow_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :name, :text, null: false
      add :category, :text, null: false
      add :is_initial?, :boolean, default: false
      add :position, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create index(:workflow_states, [:workspace_id, :workflow_id, :position])

    create table(:transitions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :workspace_id, :uuid, null: false

      add :workflow_id,
          references(:workflows,
            column: :id,
            name: "transitions_workflow_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :from_state_id,
          references(:workflow_states,
            column: :id,
            name: "transitions_from_state_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :to_state_id,
          references(:workflow_states,
            column: :id,
            name: "transitions_to_state_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :guards, {:array, :map}, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create index(:transitions, [:workspace_id, :workflow_id, :from_state_id])

    alter table(:object_types) do
      modify :workflow_id,
             references(:workflows,
               column: :id,
               name: "object_types_workflow_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:object_types, [:workspace_id, :workflow_id])
  end

  def down do
    drop_if_exists index(:object_types, [:workspace_id, :workflow_id])

    drop constraint(:object_types, "object_types_workflow_id_fkey")

    alter table(:object_types) do
      modify :workflow_id, :uuid
    end

    drop constraint(:transitions, "transitions_workflow_id_fkey")

    drop constraint(:transitions, "transitions_from_state_id_fkey")

    drop constraint(:transitions, "transitions_to_state_id_fkey")

    drop_if_exists index(:transitions, [:workspace_id, :workflow_id, :from_state_id])

    drop table(:transitions)

    drop constraint(:workflow_states, "workflow_states_workflow_id_fkey")

    drop_if_exists index(:workflow_states, [:workspace_id, :workflow_id, :position])

    drop table(:workflow_states)

    drop table(:workflows)
  end
end
