defmodule Concept.Repo.Migrations.AddChatReactions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:chat_reactions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :workspace_id, :uuid, null: false

      add :message_id,
          references(:messages,
            column: :id,
            name: "chat_reactions_message_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :membership_id,
          references(:memberships,
            column: :id,
            name: "chat_reactions_membership_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :emoji, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:chat_reactions, [:workspace_id, :message_id])

    create unique_index(:chat_reactions, [:workspace_id, :message_id, :membership_id, :emoji],
             name: "chat_reactions_unique_reaction_index"
           )
  end

  def down do
    drop constraint(:chat_reactions, "chat_reactions_message_id_fkey")

    drop constraint(:chat_reactions, "chat_reactions_membership_id_fkey")

    drop_if_exists unique_index(
                     :chat_reactions,
                     [:workspace_id, :message_id, :membership_id, :emoji],
                     name: "chat_reactions_unique_reaction_index"
                   )

    drop_if_exists index(:chat_reactions, [:workspace_id, :message_id])

    drop table(:chat_reactions)
  end
end
