defmodule Concept.Repo.Migrations.WorkspacesAndMemberships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workspaces, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :icon_emoji, :text, default: "🏠"

      add :owner_id,
          references(:users,
            column: :id,
            name: "workspaces_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:workspaces, [:slug], name: "workspaces_unique_slug_index")

    create table(:memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, default: "member"

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "memberships_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "memberships_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:memberships, [:workspace_id, :user_id],
             name: "memberships_unique_user_workspace_index"
           )
  end

  def down do
    drop constraint(:memberships, "memberships_workspace_id_fkey")

    drop constraint(:memberships, "memberships_user_id_fkey")

    drop_if_exists unique_index(:memberships, [:workspace_id, :user_id],
                     name: "memberships_unique_user_workspace_index"
                   )

    drop table(:memberships)

    drop constraint(:workspaces, "workspaces_owner_id_fkey")

    drop_if_exists unique_index(:workspaces, [:slug], name: "workspaces_unique_slug_index")

    drop table(:workspaces)
  end
end
