defmodule Concept.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:knowledge_links, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :workspace_id, :uuid, null: false

      add :source_block_id,
          references(:blocks,
            column: :id,
            name: "knowledge_links_source_block_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :target_block_id,
          references(:blocks,
            column: :id,
            name: "knowledge_links_target_block_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :kind, :text, null: false
      add :note, :text
      add :created_by_user_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(
             :knowledge_links,
             [:workspace_id, :source_block_id, :target_block_id, :kind],
             name: "knowledge_links_unique_triple_index"
           )
  end

  def down do
    drop constraint(:knowledge_links, "knowledge_links_source_block_id_fkey")

    drop constraint(:knowledge_links, "knowledge_links_target_block_id_fkey")

    drop_if_exists unique_index(
                     :knowledge_links,
                     [:workspace_id, :source_block_id, :target_block_id, :kind],
                     name: "knowledge_links_unique_triple_index"
                   )

    drop table(:knowledge_links)
  end
end
