defmodule Concept.Repo.Migrations.Wave1Participants do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages) do
      add :sender_participant_id, :uuid
      add :mentions, {:array, :uuid}, null: false, default: []
      add :addresses_host, :boolean, null: false, default: true
    end

    create table(:chat_participants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:messages) do
      modify :sender_participant_id,
             references(:chat_participants,
               column: :id,
               name: "messages_sender_participant_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:chat_participants) do
      add :workspace_id, :uuid, null: false

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "chat_participants_conversation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :membership_id,
          references(:memberships,
            column: :id,
            name: "chat_participants_membership_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :last_read_message_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:chat_participants, [:workspace_id, :membership_id])

    create index(:chat_participants, [:workspace_id, :conversation_id])

    create unique_index(:chat_participants, [:workspace_id, :conversation_id, :membership_id],
             name: "chat_participants_unique_membership_per_conversation_index"
           )
  end

  def down do
    drop constraint(:chat_participants, "chat_participants_conversation_id_fkey")

    drop constraint(:chat_participants, "chat_participants_membership_id_fkey")

    drop_if_exists unique_index(
                     :chat_participants,
                     [:workspace_id, :conversation_id, :membership_id],
                     name: "chat_participants_unique_membership_per_conversation_index"
                   )

    drop_if_exists index(:chat_participants, [:workspace_id, :conversation_id])

    drop_if_exists index(:chat_participants, [:workspace_id, :membership_id])

    alter table(:chat_participants) do
      remove :updated_at
      remove :inserted_at
      remove :last_read_message_id
      remove :membership_id
      remove :conversation_id
      remove :workspace_id
    end

    drop constraint(:messages, "messages_sender_participant_id_fkey")

    alter table(:messages) do
      modify :sender_participant_id, :uuid
    end

    drop table(:chat_participants)

    alter table(:messages) do
      remove :addresses_host
      remove :mentions
      remove :sender_participant_id
    end
  end
end
