defmodule Concept.Repo.Migrations.Bug061ChatWorkspaceId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Add workspace_id nullable first, backfill existing rows, then enforce
    # NOT NULL. global? false multitenancy requires every row to carry it
    # (BUG-061). Backfill maps a conversation to its owner's workspace and a
    # message to its conversation's workspace.
    alter table(:conversations) do
      add :workspace_id, :uuid
    end

    alter table(:messages) do
      add :workspace_id, :uuid
    end

    # Conversation -> owner's workspace (deterministic: earliest membership).
    execute("""
    UPDATE conversations c
    SET workspace_id = m.workspace_id
    FROM (
      SELECT DISTINCT ON (user_id) user_id, workspace_id
      FROM memberships
      ORDER BY user_id, inserted_at ASC
    ) m
    WHERE m.user_id = c.user_id
    """)

    # Orphan conversations (owner has no membership) -> any workspace, else
    # delete is unsafe (FK from messages); pin to the first workspace.
    execute("""
    UPDATE conversations
    SET workspace_id = (SELECT id FROM workspaces ORDER BY inserted_at ASC LIMIT 1)
    WHERE workspace_id IS NULL
    """)

    # Message -> its conversation's workspace.
    execute("""
    UPDATE messages msg
    SET workspace_id = c.workspace_id
    FROM conversations c
    WHERE c.id = msg.conversation_id
    """)

    # Any remaining nulls (shouldn't happen) -> first workspace, so NOT NULL holds.
    execute("""
    UPDATE messages
    SET workspace_id = (SELECT id FROM workspaces ORDER BY inserted_at ASC LIMIT 1)
    WHERE workspace_id IS NULL
    """)

    alter table(:conversations) do
      modify :workspace_id, :uuid, null: false
    end

    alter table(:messages) do
      modify :workspace_id, :uuid, null: false
    end
  end

  def down do
    alter table(:messages) do
      remove :workspace_id
    end

    alter table(:conversations) do
      remove :workspace_id
    end
  end
end
