defmodule Concept.Repo.Migrations.AddWorkspaceIdToApiKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:api_keys) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "api_keys_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:api_keys, "api_keys_workspace_id_fkey")

    alter table(:api_keys) do
      remove :workspace_id
    end
  end
end
