defmodule Concept.Repo.Migrations.AddParticipantPinnedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:chat_participants) do
      add :pinned_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:chat_participants) do
      remove :pinned_at
    end
  end
end
