defmodule Concept.Repo.Migrations.AddApiKeyAuth do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages) do
      add :rewritten_prompt, :text
      add :search_trace, {:array, :map}, null: false, default: []
      add :prompt_tokens, :bigint
      add :completion_tokens, :bigint
      add :latency_ms, :bigint
      add :grounding_score, :float
    end

    create table(:api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :api_key_hash, :binary, null: false
      add :expires_at, :utc_datetime_usec, null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "api_keys_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:api_keys, [:api_key_hash], name: "api_keys_unique_api_key_index")
  end

  def down do
    drop constraint(:api_keys, "api_keys_user_id_fkey")

    drop_if_exists unique_index(:api_keys, [:api_key_hash], name: "api_keys_unique_api_key_index")

    drop table(:api_keys)

    alter table(:messages) do
      remove :grounding_score
      remove :latency_ms
      remove :completion_tokens
      remove :prompt_tokens
      remove :search_trace
      remove :rewritten_prompt
    end
  end
end
