defmodule Concept.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:knowledge_token_ledger, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :workspace_id, :uuid, null: false
      add :day, :date, null: false
      add :prompt_tokens, :bigint, default: 0
      add :completion_tokens, :bigint, default: 0
      add :embed_tokens, :bigint, default: 0
      add :request_count, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:knowledge_token_ledger, [:workspace_id, :day])

    create unique_index(:knowledge_token_ledger, [:workspace_id, :day],
             name: "knowledge_token_ledger_one_per_workspace_per_day_index"
           )

    create table(:knowledge_links_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :workspace_id, :uuid, null: false

      add :version_source_id,
          references(:knowledge_links,
            column: :id,
            name: "knowledge_links_versions_version_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:knowledge_citations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :workspace_id, :uuid, null: false

      add :message_id,
          references(:messages,
            column: :id,
            name: "knowledge_citations_message_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :block_id,
          references(:blocks,
            column: :id,
            name: "knowledge_citations_block_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :page_id,
          references(:pages,
            column: :id,
            name: "knowledge_citations_page_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :rank, :bigint, null: false
      add :score, :float
      add :snippet, :text
      add :breadcrumbs, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:knowledge_citations, [:workspace_id, :block_id])

    create index(:knowledge_citations, [:workspace_id, :message_id])
  end

  def down do
    drop constraint(:knowledge_citations, "knowledge_citations_message_id_fkey")

    drop constraint(:knowledge_citations, "knowledge_citations_block_id_fkey")

    drop constraint(:knowledge_citations, "knowledge_citations_page_id_fkey")

    drop_if_exists index(:knowledge_citations, [:workspace_id, :message_id])

    drop_if_exists index(:knowledge_citations, [:workspace_id, :block_id])

    drop table(:knowledge_citations)

    drop constraint(:knowledge_links_versions, "knowledge_links_versions_version_source_id_fkey")

    drop table(:knowledge_links_versions)

    drop_if_exists unique_index(:knowledge_token_ledger, [:workspace_id, :day],
                     name: "knowledge_token_ledger_one_per_workspace_per_day_index"
                   )

    drop_if_exists index(:knowledge_token_ledger, [:workspace_id, :day])

    drop table(:knowledge_token_ledger)
  end
end
