defmodule Concept.Repo.Migrations.CreateObjectsEngine do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:records, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :workspace_id, :uuid, null: false
      add :object_type_id, :uuid, null: false
      add :title, :text, default: ""
      add :fields, :map, default: %{}
      add :state_id, :uuid
      add :assignee_id, :uuid
      add :created_by_id, :uuid
      add :page_id, :uuid
      add :position, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create index(:records, [:fields], using: "gin")

    create index(:records, [:workspace_id, :state_id])

    create index(:records, [:workspace_id, :assignee_id])

    create index(:records, [:workspace_id, :object_type_id, :position])

    create table(:record_links, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :workspace_id, :uuid, null: false

      add :from_record_id,
          references(:records,
            column: :id,
            name: "record_links_from_record_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :to_record_id,
          references(:records,
            column: :id,
            name: "record_links_to_record_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :field_def_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:record_links, [:workspace_id, :to_record_id])

    create index(:record_links, [:workspace_id, :from_record_id])

    create table(:object_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:records) do
      modify :object_type_id,
             references(:object_types,
               column: :id,
               name: "records_object_type_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :assignee_id,
             references(:users,
               column: :id,
               name: "records_assignee_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :created_by_id,
             references(:users,
               column: :id,
               name: "records_created_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :page_id,
             references(:pages,
               column: :id,
               name: "records_page_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:object_types) do
      add :workspace_id, :uuid, null: false
      add :name, :text, null: false
      add :key, :text, null: false
      add :icon, :text, default: "📋"
      add :color, :text, default: "default"
      add :workflow_id, :uuid
      add :is_system?, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create index(:object_types, [:workspace_id, :key], unique: true)

    create table(:field_defs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:record_links) do
      modify :field_def_id,
             references(:field_defs,
               column: :id,
               name: "record_links_field_def_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:field_defs) do
      add :workspace_id, :uuid, null: false

      add :object_type_id,
          references(:object_types,
            column: :id,
            name: "field_defs_object_type_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :name, :text, null: false
      add :key, :text, null: false
      add :field_type, :text, null: false
      add :required?, :boolean, default: false
      add :config, :map, default: %{}
      add :is_title?, :boolean, default: false
      add :position, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create index(:field_defs, [:workspace_id, :object_type_id, :key], unique: true)

    create index(:field_defs, [:workspace_id, :object_type_id, :position])
  end

  def down do
    drop constraint(:field_defs, "field_defs_object_type_id_fkey")

    drop_if_exists index(:field_defs, [:workspace_id, :object_type_id, :position])

    drop_if_exists index(:field_defs, [:workspace_id, :object_type_id, :key])

    alter table(:field_defs) do
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :position
      remove :is_title?
      remove :config
      remove :required?
      remove :field_type
      remove :key
      remove :name
      remove :object_type_id
      remove :workspace_id
    end

    drop constraint(:record_links, "record_links_field_def_id_fkey")

    alter table(:record_links) do
      modify :field_def_id, :uuid
    end

    drop table(:field_defs)

    drop_if_exists index(:object_types, [:workspace_id, :key])

    alter table(:object_types) do
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :is_system?
      remove :workflow_id
      remove :color
      remove :icon
      remove :key
      remove :name
      remove :workspace_id
    end

    drop constraint(:records, "records_object_type_id_fkey")

    drop constraint(:records, "records_assignee_id_fkey")

    drop constraint(:records, "records_created_by_id_fkey")

    drop constraint(:records, "records_page_id_fkey")

    alter table(:records) do
      modify :page_id, :uuid
      modify :created_by_id, :uuid
      modify :assignee_id, :uuid
      modify :object_type_id, :uuid
    end

    drop table(:object_types)

    drop constraint(:record_links, "record_links_from_record_id_fkey")

    drop constraint(:record_links, "record_links_to_record_id_fkey")

    drop_if_exists index(:record_links, [:workspace_id, :from_record_id])

    drop_if_exists index(:record_links, [:workspace_id, :to_record_id])

    drop table(:record_links)

    drop_if_exists index(:records, [:workspace_id, :object_type_id, :position])

    drop_if_exists index(:records, [:workspace_id, :assignee_id])

    drop_if_exists index(:records, [:workspace_id, :state_id])

    drop_if_exists index(:records, [:fields])

    drop table(:records)
  end
end
