defmodule Concept.Repo.Migrations.ExtendChatMessageWithScopeAndProfile do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages) do
      add :scope, :text, null: false, default: "workspace"
      add :scope_target_id, :uuid
      add :profile, :text, null: false, default: "default"
    end
  end

  def down do
    alter table(:messages) do
      remove :profile
      remove :scope_target_id
      remove :scope
    end
  end
end
