defmodule Concept.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop table(:knowledge_citations)

    drop table(:knowledge_links_versions)

    drop table(:knowledge_token_ledger)
  end

  def down do
    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually
  end
end
