defmodule Concept.Repo.Migrations.PagesAndBlocks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:pages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :workspace_id, :uuid, null: false

      add :parent_page_id,
          references(:pages,
            column: :id,
            name: "pages_parent_page_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :title, :text, default: ""
      add :icon_emoji, :text, default: "📄"
      add :cover_color, :text, default: "default"
      add :position, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create index(:pages, [:workspace_id, :parent_page_id, :position])

    create table(:blocks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :workspace_id, :uuid, null: false

      add :page_id,
          references(:pages,
            column: :id,
            name: "blocks_page_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :parent_block_id,
          references(:blocks,
            column: :id,
            name: "blocks_parent_block_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :type, :text, null: false
      add :position, :text, null: false
      add :content, :map, default: %{}
      add :props, :map, default: %{}
      add :lock_state, :text, default: "unlocked"

      add :lock_holder_id,
          references(:users,
            column: :id,
            name: "blocks_lock_holder_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :lock_acquired_at, :utc_datetime_usec
      add :lock_expires_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :state, :text, null: false, default: "unlocked"
    end

    create index(:blocks, [:workspace_id, :page_id, :parent_block_id, :position])
  end

  def down do
    drop constraint(:blocks, "blocks_page_id_fkey")

    drop constraint(:blocks, "blocks_parent_block_id_fkey")

    drop constraint(:blocks, "blocks_lock_holder_id_fkey")

    drop_if_exists index(:blocks, [:workspace_id, :page_id, :parent_block_id, :position])

    drop table(:blocks)

    drop constraint(:pages, "pages_parent_page_id_fkey")

    drop_if_exists index(:pages, [:workspace_id, :parent_page_id, :position])

    drop table(:pages)
  end
end
