defmodule Concept.Repo.Migrations.AgentRoleAndObjectsRels do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      modify :state_id,
             references(:workflow_states,
               column: :id,
               name: "records_state_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:records, "records_state_id_fkey")

    alter table(:records) do
      modify :state_id, :uuid
    end
  end
end
