defmodule Concept.Repo.Migrations.Wave5Crystallize do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      add :crystallized_page_id, :uuid
    end
  end

  def down do
    alter table(:conversations) do
      remove :crystallized_page_id
    end
  end
end
