defmodule Concept.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workspaces) do
      add :primary?, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:workspaces) do
      remove :primary?
    end
  end
end
