defmodule Concept.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:knowledge_token_ledger, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :workspace_id, :uuid, null: false
      add :day, :date, null: false
      add :prompt_tokens, :bigint, default: 0
      add :completion_tokens, :bigint, default: 0
      add :embed_tokens, :bigint, default: 0
      add :request_count, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:knowledge_token_ledger, [:workspace_id, :day])

    create unique_index(:knowledge_token_ledger, [:workspace_id, :day],
             name: "knowledge_token_ledger_one_per_workspace_per_day_index"
           )
  end

  def down do
    drop_if_exists unique_index(:knowledge_token_ledger, [:workspace_id, :day],
                     name: "knowledge_token_ledger_one_per_workspace_per_day_index"
                   )

    drop_if_exists index(:knowledge_token_ledger, [:workspace_id, :day])

    drop table(:knowledge_token_ledger)
  end
end
